#!/bin/bash

echo "============================================"
echo "  FLYQ Drone Controller - APK Build Guide"
echo "============================================"
echo ""
echo "To build an APK, you have 3 quick options:"
echo ""
echo "OPTION 1: Build via EAS CLI (Fastest - 5 minutes)"
echo "---------------------------------------------------"
echo "1. Run: npx eas-cli login"
echo "2. Run: npx eas-cli build --platform android --profile preview"
echo "3. Wait for build to complete"
echo "4. Download APK from the provided link"
echo ""
echo "OPTION 2: Build via Expo Website (Easiest)"
echo "---------------------------------------------------"
echo "1. Go to: https://expo.dev"
echo "2. Login to your account"
echo "3. Go to Projects → flyq-drone-controller → Builds"
echo "4. Click 'Build' → Select 'Android' → Choose 'APK'"
echo "5. Wait and download"
echo ""
echo "OPTION 3: I can help you login to EAS"
echo "---------------------------------------------------"
echo "If you provide your Expo credentials, I can build the APK for you."
echo ""
echo "============================================"
echo ""
echo "Your project is configured correctly:"
echo "✅ Keystore: android/app/flyq-upload.keystore"
echo "✅ EAS configuration: eas.json (preview profile = APK)"
echo "✅ AAB already built: Version 2.1.0"
echo ""
echo "Note: You already have the AAB for Play Store upload."
echo "APK is optional - mainly for direct device installation."
echo ""

